[package]
name = "fuoevolve-smtc-bridge"
version = "0.1.0"
edition = "2021"
rust-version = "1.95"
publish = false

[lib]
name = "fuoevolve_smtc_bridge"
crate-type = ["cdylib"]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.100.0", features = [
    "Media",
    "ro",
    "systemmediatransportcontrolsinterop",
    "windef",
] }
