#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
IOS_DIR="$ROOT_DIR/iosApp"
RESOURCE_DIR="$IOS_DIR/FuoEvolve/PythonResources"
BUILD_DIR="$ROOT_DIR/build/ios-python"
PYTHON_TAG="${PYTHON_APPLE_SUPPORT_TAG:-3.12-b8}"
REQUIREMENTS="${IOS_PYTHON_REQUIREMENTS:-$IOS_DIR/python/requirements-ios.txt}"
HOST_PYTHON="${HOST_PYTHON:-python3}"

mkdir -p "$RESOURCE_DIR" "$BUILD_DIR"

ASSET_URL="$("$HOST_PYTHON" - "$PYTHON_TAG" <<'PY'
import json
import sys
import urllib.request

tag = sys.argv[1]
url = f"https://api.github.com/repos/beeware/Python-Apple-support/releases/tags/{tag}"
with urllib.request.urlopen(url, timeout=30) as response:
    release = json.load(response)
for asset in release.get("assets", []):
    name = asset.get("name", "")
    if name.startswith("Python-3.12-iOS-support") and name.endswith(".tar.gz"):
        print(asset["browser_download_url"])
        break
else:
    raise SystemExit(f"no Python 3.12 iOS support asset found for {tag}")
PY
)"

ARCHIVE="$BUILD_DIR/$(basename "$ASSET_URL")"
if [ ! -f "$ARCHIVE" ]; then
    curl -L "$ASSET_URL" -o "$ARCHIVE"
fi

rm -rf "$RESOURCE_DIR/python" "$RESOURCE_DIR/app"
mkdir -p "$RESOURCE_DIR/python" "$RESOURCE_DIR/app"
tar -xzf "$ARCHIVE" -C "$RESOURCE_DIR/python" --strip-components=1

rsync -a "$ROOT_DIR/androidApp/src/main/python/fuo_mobile" "$RESOURCE_DIR/app/"

"$HOST_PYTHON" -m pip install \
    --upgrade \
    --target "$RESOURCE_DIR/app" \
    -r "$REQUIREMENTS"

find "$RESOURCE_DIR/app" -type d -name "__pycache__" -prune -exec rm -rf {} +
find "$RESOURCE_DIR/app" -type f -name "*.pyc" -delete

cat > "$RESOURCE_DIR/README.txt" <<'TXT'
Generated by scripts/prepare-ios-python.sh.
Do not edit generated Python runtime files by hand.
TXT

echo "Prepared iOS Python runtime at $RESOURCE_DIR"
