name: PR Tests

"on":
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  shared:
    name: Shared
    uses: ./.github/workflows/shared-tests.yml
    secrets:
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  android:
    name: Android
    needs: shared
    uses: ./.github/workflows/android-tests.yml
    secrets:
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  ios:
    name: iOS
    needs: shared
    uses: ./.github/workflows/ios-tests.yml

  windows:
    name: Windows
    needs: shared
    uses: ./.github/workflows/windows-tests.yml

  macos:
    name: macOS
    needs: shared
    uses: ./.github/workflows/macos-tests.yml

  linux:
    name: Linux
    needs: shared
    uses: ./.github/workflows/linux-tests.yml
